### ISSUE TITLE
Make test 

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/libvpx-os2#1]
There is one test which fails with a sigsegv after more than 900 working tests. This should be fixed one day.

**Comment by dryeo** [comment]
The official 1.3.0 repository build passed them all here, with the exception of 4 skipped.
Other then adding -Zmap to ldflags, no changes were made, did configure with --enable-shared and --disable-static

**Comment by SilvanScherrer** [comment]
seems fixed
