### ISSUE TITLE
Build an RPM of libvpx 1.13.0

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/libvpx-os2#2]
Hi, Qt6 webengine requires a newer libvpx then currently available as an RPM. It would help to have the recently released version 1.13.0 built as an RPM.
The official release builds fine and passes make test here.

**Comment by SilvanScherrer** [comment]
1.13.1 is in the works atm

**Comment by SilvanScherrer** [comment]
uploaded to exp repo

**Comment by dryeo** [comment]
Updating libvpx, libvpx-devel and libvpx-utils gives

```ERROR with transaction check vs depsolve:libvpx = 1.13.1-1.oc00 is 
needed by libvpx-utils-1.13.1-1.oc00.pentium4libvpx8.dll is needed by 
libvpx-utils-1.13.1-1.oc00.pentium4libvpx = 1.13.1-1.oc00 is needed by 
libvpx-devel-1.13.1-1.oc00.pentium4Please report this error at 
https://github.com/bitwiseworks/rpm-issues```

Looking at the libvpx rpm, it seems to have both 1.4.0-1.oc00 and 
libvpx-1.13.1-1.oc00

**Comment by SilvanScherrer** [comment]
you need to use yum install libvpx then it works. I guess this has to do with the i686 vs pentium4 switch

**Comment by dryeo** [comment]
On 11/09/23 11:47 PM, Silvan Scherrer wrote:
> you need to use yum install libvpx then it works. I guess this has to do
> with the i686 vs pentium4 switch

OK, that worked, noticed that libvpx-legacy-6 became available after I 
tried, might have been part of the problem
Thanks
